# Generated by Django 2.0.5 on 2018-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_profissional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprofissional',
            name='dataNascimento',
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='cargo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
