# Generated by Django 2.0.5 on 2018-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_profissional', '0002_auto_20180617_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='resumo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
